--liquibase formatted SQL
--changeset DKorb:5

INSERT INTO `products` VALUES (1,'Lenovo Flex 3i Chromebook','Lenovo_Flex_3i_Chromebook','<div style=\"text-align: start;\"><span style=\"font-size: 13px; color: rgb(4, 12, 19); font-family: &quot;Human BBY Digital&quot;, &quot;Human Fallback&quot;, Arial, Helvetica, sans-serif; font-weight: var(--mdb-body-font-weight);\">One of the most versatile Chromebooks on the market, the IdeaPad™ Flex 3i Chromebook 15\" merges accessibility with power, with an Intel Celeron N4500 processor to handle even the most arduous tasks without a hint of strain. Its slim and light 360° convertible design and 10 hours of battery life makes it suitable for any setting. And as a Chromebook, you can quickly access all your files, photos, music, and more. You can also talk to Google to help you multitask, control your smart home devices or manage your day.</span><br></div>','2022-06-01 13:51:09','2022-06-01 13:51:09',1,1,429,'lenovo_flex_3i.jpg',8,4);
INSERT INTO `products` VALUES (2,'Dell Inspiron 2','Dell_Inspiron_2','<div style=\"text-align: left;\">The Inspiron range of laptops and 2-in1s are thoughtfully designed so you can stay connected wherever you are with long-lasting battery life. Equipped with the latest processors, graphics, and thermal solutions; your PC runs quickly and smoothly as you connect with confidence. Optimized with technology that simplifies your life, Inspiron laptops and 2-in-1s offer a range of easy-to-use features all packaged in a minimalist and modern design. A newly designed and ergonomically positioned lift hinge increases comfort for a better typing experience when on chat, writing lengthy emails or connecting to your world. And that’s not all, your Inspiron, is now environmentally conscious – The Inspiron compliments not just your style but also your values.<br></div>','2022-06-01 14:06:35','2022-06-01 14:06:35',1,1,849,'Dell_Inspiron_2.jpg',4,4);
INSERT INTO `products` VALUES (3,'Samsung Odyssey G7','Samsung_Odyssey_G7','<div style=\"text-align: left;\"><div><span style=\"font-size: var(--mdb-body-font-size); font-weight: var(--mdb-body-font-weight);\">Take the fight to any gaming challenge, with Samsung’s ultimate 28” gaming monitor, the G70A - equipped with a 1ms response time, UHD 4K resolution, 144hz refresh rate with G-Sync and FreeSync Premium support, HDMI 2.1, and fully customizable Odyssey Infinity Core lighting.</span><br></div></div>',NULL,'2022-06-01 14:15:21',1,1,629,'samsung_odyssey_g7.jpg',9,7);
INSERT INTO `products` VALUES (4,'Samsung T55 Series','Samsung_T55_Series','<div style=\"text-align: left;\">27\" Curved Monitor with optimal curvature 1000R<br></div>','2022-06-01 14:13:01','2022-06-01 14:13:01',1,1,219,'samsung_t55_series.jpg',9,7);
INSERT INTO `products` VALUES (5,'Samsung Odyssey AG3','Samsung_Odyssey_AG3','<div style=\"text-align: left;\">Performance oriented gamers require a monitor that can keep up. With up to 144hz refresh rates, extreme 1ms MPRT response times and full Freesync Premium Pro support, you can be sure that the G30A has the performance to keep up with your skill.<br></div>','2022-06-01 14:15:02','2022-06-01 14:15:02',1,1,199,'samsung_odyssey_ag3.jpg',2,7);
INSERT INTO `products` VALUES (6,'Sony Alpha a7 III','Sony_Alpha_a7_III','<div style=\"text-align: left;\">Capture stunning portraits and beautiful action shots with this Sony a7 III full-frame mirrorless camera with FE 28-70mm standard zoom lens. Optical SteadyShot image stabilization delivers blur-free, crisp images, while the seven-blade circular aperture delivers more natural-looking bokeh effects. With its dust- and moisture-resistant design, this camera is ideal for both indoor and outdoor photo shoots.<br></div>','2022-06-01 14:20:34','2022-06-01 14:20:34',1,1,2199,'sony_alpha_a7_iii.jpg',7,2);
INSERT INTO `products` VALUES (7,'Sony Alpha a6000','Sony_Alpha_a6000','<div style=\"text-align: left;\">Sony Alpha a6000 Mirrorless Camera Two Lens Kit with 16-50mm and 55-210mm Lenses: With its 24.3-megapixel Exmor CMOS sensor and interchangeable lenses, this mirrorless camera allows you to capture sharp, realistic pictures for yourself or your clients. If you want to share stored photos, simply connect wireless devices to the camera\'s built-in Wi-Fi. .<br></div>','2022-06-01 14:23:05','2022-06-01 14:23:05',1,1,999,'sony_alpha_a6000.jpg',7,2);
INSERT INTO `products` VALUES (8,'HP ENVY 2','HP_ENVY_2','<div style=\"text-align: left;\">See and do it all in perfect color: The ENVY x360 15 gives you a dazzling high definition screen with accurate color and more ways to make your masterpiece with HP Quick Drop file sharing. Power to set your creativity free: Unleash your creativity with the power and performance of an AMD Ryzen™ processor and Radeon™ Graphics that make every task incredibly fast and efficient. Peace of mind at your fingertips: Keep it confidential with privacy camera shutter key to turn camera off and a mute mic button for private conversations.<br></div>','2022-06-01 14:25:17','2022-06-01 14:25:17',1,1,819,'hp_envy_2.jpg',5,4);
INSERT INTO `products` VALUES (9,'Samsung 870 EVO 1TB SATA','Samsung_870_EVO_1TB_SATA','<div style=\"text-align: left;\">The perfect choice for creators, IT professionals or everyday users, the latest 870 EVO has indisputable performance, reliability and compatibility built upon Samsung’s pioneering technology.<br></div>','2022-06-01 14:33:31','2022-06-01 14:33:31',1,1,99,'samsung_870_evo.jpg',9,3);
INSERT INTO `products` VALUES (10,'Samsung 980 PRO 2TB','Samsung_980_PRO_2TB','<div style=\"text-align: left;\">Unleash the power of the Samsung 980 PRO PCIe 4.0 NVMe Gen4 SSD for next-level computing. 980 PRO delivers 2x the data transfer rate of PCIe 3.0, while maintaining compatibility with PCIe 3.0.¹ ¹The NVM Express® design mark is a registered trademark of NVM Express, Inc.* Results are based on a comparison with Samsung PCIe 3.0 NVMe SSDs and SATA SSDs. PS5 compatible with heatsink as recommended by Sony; heatsink sold separately.<br></div>','2022-06-01 14:36:21','2022-06-01 14:36:21',1,1,289,'samsung_980_pro.jpg',9,3);
INSERT INTO `products` VALUES (11,'ASUS NVIDIA GeForce RTX 3060 V2 12GB','ASUS_NVIDIA_GeForce_RTX_3060_V2_12GB','<div style=\"text-align: left;\">From top to bottom, the ROG Strix GeForce RTX 3060 has been designed to push performance boundaries. A fresh design and more metal surrounds a grouping of Axial-tech fans that leverage a new rotation scheme.<br></div>','2022-06-01 15:50:04','2022-06-01 15:50:04',1,1,489,'asus_nvidia_rtx_3060_v2.jpg',6,10);
INSERT INTO `products` VALUES (12,'BenQ EW328OU','BenQ_EW328OU','<div style=\"text-align: left;\">Enjoy your favourite games with clear visuals and vivid colours on this BenQ 32\" Ultra HD gaming monitor. This Ultra HD monitor with 3840 x 2160 native resolution features HDRi technology that adjusts brightness levels based on ambient lighting conditions to give you realistic images. Its 5ms GtG response time and 60Hz refresh rate give you smooth, lag-free motion.<br></div>','2022-06-01 15:52:26','2022-06-01 15:52:26',1,1,699,'benq_ew3280u.jpg',1,7);
INSERT INTO `products` VALUES (13,'BenQ EW3270U','BenQ_EW3270U','<div style=\"text-align: left;\">Watch 4K and HDR content with this 32-inch BenQ LED monitor. Its Brightness Intelligence Plus Technology detects ambient lighting conditions for optimal adjustment of display settings while preserving the cinematic quality of videos. This BenQ LED monitor has preset low blue light settings for multimedia, web-surfing, reading and office modes to support eye safety.<br></div>','2022-06-01 15:54:14','2022-06-01 15:54:14',1,1,399,'benq_ew3327ou.jpg',1,7);
INSERT INTO `products` VALUES (14,'Acer Nitro 5','Acer_Nitro_5','<div style=\"text-align: left;\">Dominate the battlefield with Acer’s new Nitro 5 gaming laptop, including everything you need to take control of the action. The powerful Nitro 5 laptop was developed to deliver an iconic gaming experience courtesy of the many awesome features inside, including its 11th Gen Intel® Core™ processor and high-performance NVIDIA® GeForce GTX 1650 graphics—that’s powered by NVIDIA Turing™ GPU architecture! Next, toss in its quick 15.6” FHD IPS 144Hz refresh rate display, awesome mobility, advanced cooling and stellar audio capabilities, and all of the other gaming-rich features, and you quickly see why the Nitro 5 delivers a knockout blow to the competition!<br></div>','2022-06-01 16:03:58','2022-06-01 16:03:58',1,1,679,'acer_nitro_5.jpg',12,4);
INSERT INTO `products` VALUES (15,'Acer Chromebook 315','Acer_Chromebook_315','<div><div style=\"text-align: left;\">Be dialed in—all the time, everywhere and anywhere—with the Acer Chromebook 315. Recognized as the perfect multi-media companion, this special machine is super thin, extra light and delivers unmatched value in today’s fast-paced, technology-driven world. It features an impressive HDR camera, fast wireless connectivity and a long-lasting battery life, so you can run your favorite Google apps or access your photos, videos, music and documents—all day long.</div></div><div><br></div>','2022-06-01 16:06:05','2022-06-01 16:06:05',1,1,179,'acer_chromebook_315.jpg',12,4);
INSERT INTO `products` VALUES (16,'ASUS ROG Gaming Desktop Intel Core i7-11700KF','ASUS_ROG_Gaming_Desktop_Intel_Core_i7-11700KF','<div><div style=\"text-align: left;\">Annihilate your competition with this ASUS ROG gaming desktop. The Intel Core i7 processor and 16GB of RAM deliver rapid performance during fast-paced action, while the 2TB HDD and a 512GB SSD provide plenty of storage for large files and downloads. This Bluetooth-enabled ASUS ROG gaming computer features an NVIDIA GeForce RTX 3080 graphics card for tear-free rendering of 4K games</div></div><div><br></div>','2022-06-01 16:08:47','2022-06-01 16:08:47',1,1,2099,'asus_rog_gaming_desktop.jpg',12,1);
INSERT INTO `products` VALUES (17,'HP OMEN Gaming Desktop AMD Ryzen 5600G','HP_OMEN_Gaming_Desktop_AMD_Ryzen_5600G','<div><div style=\"text-align: left;\">With great power comes this: The OMEN 30L Gaming Desktop PC lives for the thrill of the chase, never leaves a friend behind, and makes a mean midnight snack of action and adventure. Meet your new best friend, packing an AMD Ryzen™ processor and an AMD Radeon™ graphics card. Do how you do: OMEN Gaming Hub’s growing list of customization and optimization features gives you the power to dial-in your game and tailor-make your mark. With OMEN Light Studio, you can tailor make everything with your mark. Your game never looked so good: Sure, it\'s what\'s inside that counts, but it\'s what\'s outside that gets the looks. With tempered glass front and side panels, a full-metal frame, and complete RGB control, we made this PC for people who know that style points count on the final scoreboard of life.</div></div><div><br></div>','2022-06-01 16:16:09','2022-06-01 16:16:09',1,1,1349,'hp_omen_gaming_desktop.jpg',5,1);
INSERT INTO `products` VALUES (18,'Samsung Galaxy S21 FE 5G','Samsung_Galaxy_S21_FE_5G','<div style=\"text-align: left;\">Take your everyday experiences to the next level with the phone that\'s designed to fuel the passions of every fan. Whether you\'re a gaming guru, social star or fashionista, Samsung Galaxy S21 FE 5G is jam-packed with features that help you get more out of whatever you\'re into, including an All-Day Intelligent Battery, a powerful processor, a smooth and strong display, a triple-lens camera and more. Plus, choose from four colors for a stylish look that will set off your fan vibe.<br></div>','2022-06-01 16:18:54','2022-06-01 16:18:54',1,1,499,'samsung_galaxy_s21_fe_5g.jpg',9,5);
INSERT INTO `products` VALUES (19,'Samsung Galaxy Note 10','Samsung_Galaxy_Note_10','<div style=\"text-align: left;\">The Galaxy Note10 isn\'t just a new smartphone. It\'s a gaming console. A film studio. It\'s a computer with an intelligent pen control—and it\'s all in one device. The Galaxy Note10\'s cutting-edge battery intelligence with super-fast charging ensures you won\'t be left powerless. Download photos and videos, stream content, even game online in the busiest of places at incredible speeds with a powerful processor and the 2.0Gbps LTE connection of Galaxy Note10. High-polish metal and glass meld in an impressively slim design to help the Galaxy Note10 glide from hand to pocket as easily as you glide from fitness to playlists. Galaxy Note10\'s Dynamic AMOLED screen gives you seemingly endless light and only a tiny, front-facing camera lens, so you have brilliant color in all conditions.<br></div>',NULL,'2022-06-01 16:26:11',1,1,429,'samsung_galaxy_note_10.jpg',9,5);
INSERT INTO `products` VALUES (20,'Sony Xperia 1 III 5G','Sony_Xperia_1_III_5G','<div style=\"text-align: left;\">Experience breathtaking speed in in your creative, entertainment or gaming from the World’s first 120Hz immersive 6.5” 4K HDR OLED display to the triple camera and four focal lengths which features Real-time autofocus even when shooting extended telephoto or up to 20fps continuous image capture.<br></div>','2022-06-01 16:29:44','2022-06-01 16:29:44',1,1,1199,'sony_xperia_1_iii.jpg',7,5);
INSERT INTO `products` VALUES (21,'Lenovo - ThinkVision T22','Lenovo_-_ThinkVision_T22','<div style=\"text-align: left; \">Collaborate and hold meetings and video conferencing with the 21.5-inch ThinkVision T22v-20 that has a built-in camera, microphone, and speakers. With an integrated IR camera and Windows Hello, you can safely log in without a password.<br></div>','2022-06-06 13:47:20','2022-06-06 13:47:20',1,1,249,'lenovo_thinkvision_t22.jpg',8,7);
INSERT INTO `products` VALUES (22,'Lenovo G27-20','Lenovo_G27-20','<div style=\"text-align: left; \">&nbsp;Lenovo G27-20’s got game. Let’s start with a look at its 27-inch 1920 x 1080 full HD resolution In-Plane Switching panel display that delivers startlingly life-like lighting effects to gameplay in a luminous 400 cd/m2, thanks to HDR decoding on-the-fly. It never misses a beat, even in the most intense moments, because its speedy 144Hz refresh rate and 1ms MPRT response time, coupled with AMD FreeSync™ Premium, remove image stutter, break, tear and streak from the experience, leaving a smooth, fluid unspoilt session.&nbsp;<br></div>','2022-06-06 13:49:31','2022-06-06 13:49:31',1,1,270,'lenovo_g2720.jpg',8,7);
INSERT INTO `products` VALUES (23,'Kingston - A400','Kingston_-_A400','<div><span style=\"text-align: left; font-size: var(--mdb-body-font-size); font-weight: var(--mdb-body-font-weight);\">Boost the data storage speed and capacity of your desktop or laptop computer with this Kingston solid-state drive. It has read and write speeds 10 times greater than a standard hard drive to increase multitasking speed. This Kingston solid-state drive has no moving parts and resists shock and vibration for dependable performance.</span><br></div>','2022-06-06 14:08:17','2022-06-06 14:08:17',1,1,85,'kingston_a400.jpg',13,3);
INSERT INTO `products` VALUES (24,'Kingston - NV1','Kingston_-_NV1','<div style=\"text-align: left; \"><span style=\"font-size: var(--mdb-body-font-size); font-weight: var(--mdb-body-font-weight);\">Kingston’s NV1 NVMe PCIe SSD is a substantial storage solution that offers read/write Kingston’s NV1 NVMe PCIe SSD is a substantial storage solution that offers read/write speeds up to 2,100/1,700MB/s, which is 3 to 4 times faster than a SATA-based SSD, and 35 times faster than a traditional hard drive. NV1 works with lower power, lower heat, and quicker loading time. The efficient performance and single-sided M.2 2280 (22x80mm) design makes NV1 ideal for thin notebooks and systems with limited space.speeds up to 2,100/1,700MB/s, which is 3 to 4 times faster than a SATA-based SSD, and 35 times faster than a traditional hard drive. NV1 works with lower power, lower heat, and quicker loading time. The efficient performance and single-sided M.2 2280 (22x80mm) design makes NV1 ideal for thin notebooks and systems with limited space.</span><br></div>','2022-06-06 14:09:51','2022-06-06 14:09:51',1,1,162,'kingston_nv1.jpg',13,3);
INSERT INTO `products` VALUES (25,'OnePlus 10 Pro 5G','OnePlus_10_Pro_5G','<div style=\"text-align: left; \"><span style=\"font-size: var(--mdb-body-font-size); font-weight: var(--mdb-body-font-weight);\">The OnePlus 10 Pro is “ultra” in every aspect. Capture breath-taking photos and videos with the new OnePlus Billion Color Solution, an even wider 150° Ultra-Wide Camera, and more. The 6.7” QHD+ display portrays stunning colors for all viewing content, and also adjusts dynamically from 1Hz up to 120Hz, giving you a silky-smooth user experience. Equipped with the latest Snapdragon 8th Gen Mobile</span><br></div>','2022-06-06 14:12:01','2022-06-06 14:12:01',1,1,899,'oneplus_10_pro.jpg',14,5);
INSERT INTO `products` VALUES (26,'OnePlus - Nord N200','OnePlus_-_Nord_N200','<div><div><br></div><div style=\"text-align: left; \">It’s 5G for all with the OnePlus Nord N200 5G, enabling blazing fast upload and download speeds. The large, clear 90Hz Full HD display puts all day immersive entertainment in the palm of your hands. Powered by a massive 5000mAh battery, you can rest assured that the Nord N200 5G can handle all your movies, TV shows, and games without breaking a sweat.</div></div>','2022-06-06 14:13:47','2022-06-06 14:13:47',1,1,239,'oneplus_nord_n200.jpg',14,5);

INSERT INTO `product_details` VALUES (1,'Screen Size','15.6 inches',1);
INSERT INTO `product_details` VALUES (2,'Screen Resolution','1920 x 1080 (Full HD)',1);
INSERT INTO `product_details` VALUES (3,'Touch Screen','Yes',1);
INSERT INTO `product_details` VALUES (4,'Processor Model','Intel Celeron',1);
INSERT INTO `product_details` VALUES (5,'RAM','4 GB',1);
INSERT INTO `product_details` VALUES (6,'Battery Life','10 hours',1);
INSERT INTO `product_details` VALUES (7,'System Architecture','64-bit',1);
INSERT INTO `product_details` VALUES (8,'Screen Size','14 inches',2);
INSERT INTO `product_details` VALUES (9,'Screen Resolution','1920 x 1080 (Full HD)',2);
INSERT INTO `product_details` VALUES (10,'Touch Screen','Yes',2);
INSERT INTO `product_details` VALUES (11,'Processor Model','Intel 11th Generation Core i5',2);
INSERT INTO `product_details` VALUES (12,'Processor Speed (up to)','2.4 gigahertz',2);
INSERT INTO `product_details` VALUES (13,'Storage Type','SSD',2);
INSERT INTO `product_details` VALUES (14,'Refresh Rate','144Hz',3);
INSERT INTO `product_details` VALUES (15,'Maximum Resolution','3840 x 2160',3);
INSERT INTO `product_details` VALUES (16,'Native Resolution','3840 x 2160',3);
INSERT INTO `product_details` VALUES (17,'Panel Type','IPS',3);
INSERT INTO `product_details` VALUES (18,'Response Time','1 milliseconds',3);
INSERT INTO `product_details` VALUES (19,'Refresh Rate','75Hz',4);
INSERT INTO `product_details` VALUES (20,'Maximum Resolution','1920 x 1080',4);
INSERT INTO `product_details` VALUES (21,'Native Resolution','1920 x 1080',4);
INSERT INTO `product_details` VALUES (22,'Response Time','4 milliseconds',4);
INSERT INTO `product_details` VALUES (23,'Panel Type','VA',4);
INSERT INTO `product_details` VALUES (24,'Screen Size','27 inches',4);
INSERT INTO `product_details` VALUES (25,'Refresh Rate','144Hz',5);
INSERT INTO `product_details` VALUES (26,'Maximum Resolution','1920 x 1080',5);
INSERT INTO `product_details` VALUES (27,'Native Resolution','1920 x 1080',5);
INSERT INTO `product_details` VALUES (28,'Response Time','1 milliseconds',5);
INSERT INTO `product_details` VALUES (29,'Panel Type','VA',5);
INSERT INTO `product_details` VALUES (30,'Screen Size','27 inches',5);
INSERT INTO `product_details` VALUES (31,'Lens Mount Compatibility','Sony E-Mount, Sony E-Mount (Full-Frame)',6);
INSERT INTO `product_details` VALUES (32,'Eye Autofocus (Eye AF)','Yes',6);
INSERT INTO `product_details` VALUES (33,'Image Sensor Type','CMOS',6);
INSERT INTO `product_details` VALUES (34,'Image Sensor Size','35mm Full Frame (36 x 24 mm)',6);
INSERT INTO `product_details` VALUES (35,'Burst Rate','5 frames per second',6);
INSERT INTO `product_details` VALUES (36,'Video Resolution','4K (2160p)',6);
INSERT INTO `product_details` VALUES (37,'Maximum Video Frame Rate','Up to 60 fps',6);
INSERT INTO `product_details` VALUES (38,'Image Sensor Size','APS-C (23.6 x 15.7 mm)',7);
INSERT INTO `product_details` VALUES (39,'Eye Autofocus (Eye AF)','Yes',7);
INSERT INTO `product_details` VALUES (40,'Burst Rate','11 frames per second',7);
INSERT INTO `product_details` VALUES (41,'Maximum Focal Length','210 millimeters',7);
INSERT INTO `product_details` VALUES (42,'Minimum Focal Length','16 millimeters',7);
INSERT INTO `product_details` VALUES (43,'Effective Pixels','24.3 megapixels',7);
INSERT INTO `product_details` VALUES (44,'Maximum Video Frame Rate','Up to 60 fps',7);
INSERT INTO `product_details` VALUES (45,'Video Resolution','Full HD (1080p)',7);
INSERT INTO `product_details` VALUES (46,'Screen Size','15.6 inches',8);
INSERT INTO `product_details` VALUES (47,'Screen Resolution','1920 x 1080 (Full HD)',8);
INSERT INTO `product_details` VALUES (48,'Touch Screen','Yes',8);
INSERT INTO `product_details` VALUES (49,'Processor Model','AMD Ryzen 5 5000 Series',8);
INSERT INTO `product_details` VALUES (50,'Storage Type','SSD',8);
INSERT INTO `product_details` VALUES (51,'Total Storage Capacity','256 GB',8);
INSERT INTO `product_details` VALUES (52,'RAM','8 GB',8);
INSERT INTO `product_details` VALUES (53,'Storage Capacity','1000 GB',9);
INSERT INTO `product_details` VALUES (54,'Storage Drive Type','SSD',9);
INSERT INTO `product_details` VALUES (55,'Maximum Data Transfer Rate','560 mb/s',9);
INSERT INTO `product_details` VALUES (56,'Maximum Read Speed','560 mb/s',9);
INSERT INTO `product_details` VALUES (57,'Maximum Write Speed','530 mb/s',9);
INSERT INTO `product_details` VALUES (58,'Form Factor','2.5 in.',9);
INSERT INTO `product_details` VALUES (59,'Interface(s)','SATA',9);
INSERT INTO `product_details` VALUES (60,'Storage Capacity','2000 GB',10);
INSERT INTO `product_details` VALUES (61,'Storage Drive Type','SSD',10);
INSERT INTO `product_details` VALUES (62,'Maximum Data Transfer Rate','7100 mb/s',10);
INSERT INTO `product_details` VALUES (63,'Form Factor','M.2 2280',10);
INSERT INTO `product_details` VALUES (64,'Interface(s)','PCIe Gen 4 x4',10);
INSERT INTO `product_details` VALUES (65,'Maximum Digital Resolution','8K (4320p)',11);
INSERT INTO `product_details` VALUES (66,'Video Memory Capacity','12 GB',11);
INSERT INTO `product_details` VALUES (67,'Type of Memory (RAM)','GDDR6',11);
INSERT INTO `product_details` VALUES (68,'Interface(s)','PCI Express 4.0',11);
INSERT INTO `product_details` VALUES (69,'GPU','NVIDIA GeForce RTX 3060',11);
INSERT INTO `product_details` VALUES (70,'Brand','ASUS',11);
INSERT INTO `product_details` VALUES (71,'Refresh Rate','60Hz',12);
INSERT INTO `product_details` VALUES (72,'Maximum Resolution','3840 x 2160',12);
INSERT INTO `product_details` VALUES (73,'Native Resolution','3840 x 2160',12);
INSERT INTO `product_details` VALUES (74,'Response Time','5 milliseconds',12);
INSERT INTO `product_details` VALUES (75,'Panel Type','IPS',12);
INSERT INTO `product_details` VALUES (76,'Screen Size','32 inches',12);
INSERT INTO `product_details` VALUES (77,'Brand','BenQ',12);
INSERT INTO `product_details` VALUES (78,'Refresh Rate','60Hz',13);
INSERT INTO `product_details` VALUES (79,'Maximum Resolution','3840 x 2160',13);
INSERT INTO `product_details` VALUES (80,'Native Resolution','3840 x 2160',13);
INSERT INTO `product_details` VALUES (81,'Response Time','4 milliseconds',13);
INSERT INTO `product_details` VALUES (82,'Screen Size','32 inches',13);
INSERT INTO `product_details` VALUES (83,'Brand','BenQ',13);
INSERT INTO `product_details` VALUES (84,'Screen Size','15.6 inches',14);
INSERT INTO `product_details` VALUES (85,'Screen Resolution','1920 x 1080 (Full HD)',14);
INSERT INTO `product_details` VALUES (86,'Touch Screen','No',14);
INSERT INTO `product_details` VALUES (87,'Processor Model','Intel 11th Generation Core i5',14);
INSERT INTO `product_details` VALUES (88,'Storage Type','SSD',14);
INSERT INTO `product_details` VALUES (89,'Total Storage Capacity','256 GB',14);
INSERT INTO `product_details` VALUES (90,'Solid State Drive Capacity','256 GB',14);
INSERT INTO `product_details` VALUES (91,'System Memory (RAM)','8 GB',14);
INSERT INTO `product_details` VALUES (92,'Screen Size','15.6 inches',15);
INSERT INTO `product_details` VALUES (93,'Screen Resolution','1366 x 768 (HD)',15);
INSERT INTO `product_details` VALUES (94,'Touch Screen','No',15);
INSERT INTO `product_details` VALUES (95,'Processor Model','Intel Celeron',15);
INSERT INTO `product_details` VALUES (96,'Processor Model Number','Intel® Celeron® N4000 Dual-Core',15);
INSERT INTO `product_details` VALUES (97,'Processor Speed (up to)','2.6 gigahertz',15);
INSERT INTO `product_details` VALUES (98,'System Memory (RAM)','4 GB',15);
INSERT INTO `product_details` VALUES (99,'Processor Model','Intel 11th Generation Core i7',16);
INSERT INTO `product_details` VALUES (100,'Processor Model Number','i7-11700KF',16);
INSERT INTO `product_details` VALUES (101,'Storage Type','HDD, SSD',16);
INSERT INTO `product_details` VALUES (102,'Total Storage Capacity','2512 GB',16);
INSERT INTO `product_details` VALUES (103,'Solid State Drive Capacity','512 GB',16);
INSERT INTO `product_details` VALUES (104,'Graphics','NVIDIA GeForce RTX 3080',16);
INSERT INTO `product_details` VALUES (105,'System Memory (RAM)','16 GB',16);
INSERT INTO `product_details` VALUES (106,'Operating System','Windows 11 Home',16);
INSERT INTO `product_details` VALUES (107,'Processor Model','AMD Ryzen 5 5000 Series',17);
INSERT INTO `product_details` VALUES (108,'Processor Model Number','ARyzen 5 5600G Processor',17);
INSERT INTO `product_details` VALUES (109,'Processor Speed (up to)','3.9 gigahertz',17);
INSERT INTO `product_details` VALUES (110,'Storage Type','SSD',17);
INSERT INTO `product_details` VALUES (111,'Total Storage Capacity','1000 GB',17);
INSERT INTO `product_details` VALUES (112,'System Memory (RAM)','16 GB',17);
INSERT INTO `product_details` VALUES (113,'Graphics','AMD Radeon RX 6600 XT',17);
INSERT INTO `product_details` VALUES (114,'Operating System','Windows 11 Home',17);
INSERT INTO `product_details` VALUES (115,'Wireless Technology','2G, 3G, 4G, 5G',18);
INSERT INTO `product_details` VALUES (116,'Operating System','Android 12',18);
INSERT INTO `product_details` VALUES (117,'Internal Memory','128 gigabytes',18);
INSERT INTO `product_details` VALUES (118,'Screen Size','6.4 inches',18);
INSERT INTO `product_details` VALUES (119,'Phone Memory (RAM)','6 GB',18);
INSERT INTO `product_details` VALUES (120,'Front-Facing Camera','32 megapixels',18);
INSERT INTO `product_details` VALUES (121,'Wireless Technology','2G, 3G, 4G, 4G LTE',19);
INSERT INTO `product_details` VALUES (122,'Operating System','Android 9.0 Pie',19);
INSERT INTO `product_details` VALUES (123,'Internal Memory','256 GB',19);
INSERT INTO `product_details` VALUES (124,'Screen Size','6.3 inches',19);
INSERT INTO `product_details` VALUES (125,'Water Resistant','No',19);
INSERT INTO `product_details` VALUES (126,'Charging Interface(s)','USB 2.0',19);
INSERT INTO `product_details` VALUES (127,'Wireless Technology','5G, 4G, 4G LTE, 3G, GSM',20);
INSERT INTO `product_details` VALUES (128,'Operating System','Android 11',20);
INSERT INTO `product_details` VALUES (129,'Internal Memory','256 GB',20);
INSERT INTO `product_details` VALUES (130,'Screen Size','6.5 inches',20);
INSERT INTO `product_details` VALUES (131,'Phone Memory (RAM)','12 GB',20);
INSERT INTO `product_details` VALUES (132,'Water Resistant','Yes',20);
INSERT INTO `product_details` VALUES (133,'Refresh Rate','60Hz',21);
INSERT INTO `product_details` VALUES (134,'Maximum Resolution','1920x1080',21);
INSERT INTO `product_details` VALUES (135,'Response Time','4 milliseconds',21);
INSERT INTO `product_details` VALUES (136,'Panel Type','IPS',21);
INSERT INTO `product_details` VALUES (137,'Screen Size','21.5 inches',21);
INSERT INTO `product_details` VALUES (138,'HDMI inputs','1',21);
INSERT INTO `product_details` VALUES (139,'Refresh Rate','144Hz',22);
INSERT INTO `product_details` VALUES (140,'Maximum Resolution','1920 x 1080',22);
INSERT INTO `product_details` VALUES (141,'Native Resolution','1920 x 1080',22);
INSERT INTO `product_details` VALUES (142,'Response Time','1 milliseconds',22);
INSERT INTO `product_details` VALUES (143,'Panel Type','IPS',22);
INSERT INTO `product_details` VALUES (144,'Screen Size','27 inches',22);